services:
  app:
    container_name: auth-demo
    image: auth-demo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=local
    ports:
      - "${HOST_PORT:-9999}:8080"
    volumes:
      - .:/app
